CourtneyHutchin/BlogIT

README.md

Closes #1 
Created ReadMe file, it will need to be edited in the future as we continue to play and flush it out.

Issue#1 read me

---

BlogIT/Views/MediaPage/MainMediaPage.cshtml

Closes #6 
Created a basic view for the media view, will need to then make the controller and connect the views next.

Issue#6 create media view

---

BlogIT/Controllers/MainMediaController.cs

Closes #7 
Created a standard media controller, need to set different permissions to adjust workflow.

Created Standard controller

---

BlogIT/Views/About Me/AboutMePage.cshtml

Created About Me Page View

---

BlogIT/Controllers/AboutMeController.cs
BlogIT/Views/About Me/AboutMePage.cshtml
BlogIT/Views/AboutMe/AboutMePage.cshtml
BlogIT/Views/Shared/_Layout.cshtml

Issue#9 about me controller

---

BlogIT/Models/BlogPost.cs

Issue#11 blog model

---

BlogIT/Controllers/BlogController.cs
BlogIT/Data/ApplicationDbContext.cs
BlogIT/Data/BlogDB.cs
BlogIT/Data/Migrations/20200730220851_Initial.Designer.cs
BlogIT/Data/Migrations/20200730220851_Initial.cs
BlogIT/appsettings.json

Issue#20 create db

---

BlogIT/Areas/Identity/Pages/Account/Register.cshtml

Commented out external authentication services div

---

BlogIT/Views/Shared/_Layout.cshtml

Unlinked the Privacy policy page

---

BlogIT/BlogIT.csproj
BlogIT/Controllers/BlogController.cs
BlogIT/Data/BlogDB.cs
BlogIT/Data/Migrations/20200806193847_TestCRUD.Designer.cs
BlogIT/Data/Migrations/20200806193847_TestCRUD.cs
BlogIT/Data/Migrations/20200806195449_MoreCrud.Designer.cs
BlogIT/Data/Migrations/20200806195449_MoreCrud.cs
BlogIT/Views/Blog/Add.cshtml
BlogIT/Views/Blog/BlogPostIndex.cshtml
BlogIT/Views/Blog/Delete.cshtml
BlogIT/Views/Blog/Edit.cshtml
BlogIT/Views/Shared/_Layout.cshtml

Issue#22 blog post crud

---

BlogIT/Views/Blog/BlogPostIndex.cshtml

Redesigned the BlogView to be more appealing.

---

BlogIT/Areas/Identity/Pages/Account/Register.cshtml.cs
BlogIT/Views/Blog/BlogPostIndex.cshtml

Closes #34 
Added some role requirements to view CRUD

Issue#34 create roles reg/login

---

BlogIT/Controllers/MediaController.cs
BlogIT/Views/Media/MainMediaPage.cshtml

Issue#51 fix media api

---

BlogIT/Views/Blog/Add.cshtml
BlogIT/Views/Blog/Edit.cshtml

Changed textbox <input> tag to <textarea>

---

BlogIT/Views/Media/MainMediaPage.cshtml

Modified Media page styles and content

---

BlogIT/Views/Shared/_Layout.cshtml

Issue#59 remove about me link

---

BlogIT/Views/Home/Index.cshtml

Altered page content

---

BlogIT/Areas/Identity/Pages/Account/Login.cshtml

Removed Excess Text

---

BlogIT/Views/Home/Index.cshtml

Removed Excesss Code

---

BlogIT/Views/Home/Index.cshtml

Updated the hex code for the H2

---

BlogIT/Controllers/AboutMeController.cs
BlogIT/Controllers/BlogController.cs
BlogIT/Controllers/HomeController.cs

Updated documentation to Blog Controller, Home, AboutMe

---

BlogIT/Data/ApplicationDbContext.cs
BlogIT/Data/BlogDB.cs
BlogIT/Models/IdentityHelper.cs

Added Documentation to DB related code
